version: "3" # docker-composeのバージョンを指定
services:
  app:
    container_name: springsample_app
    build:
      context: ../../
      dockerfile: ./docker/local/java/Dockerfile
    working_dir: /app
    volumes:
      - ../../../SpringSample:/app:cached
    environment:
      MYSQL_HOST: springsample_db
      DATABASE_NAME: local_db
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root
    ports:
      - "8080:8080"
    privileged: true
    tty: true
    command: ./gradlew bootRun
    networks:
      - spring-sample-network

  mysql:
    container_name: springsample_db
    build:
      context: ../../
      dockerfile: ./docker/local/mysql/Dockerfile
    ports:
      - "3306:3306"
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --default-authentication-plugin=mysql_native_password
    environment:
      TZ: "Asia/Tokyo"
      MYSQL_DATABASE: local_db
      MYSQL_USER: test
      MYSQL_PASSWORD: testtest
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - "./mysql/init:/docker-entrypoint-initdb.d"
    networks:
      - spring-sample-network

networks:
  spring-sample-network:
    driver: bridge
