DROP DATABASE IF EXISTS local_db;
CREATE DATABASE local_db;
USE local_db;

DROP TABLE IF EXISTS sample;
CREATE TABLE name (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name TEXT NOT NULL
) DEFAULT CHARACTER SET=utf8;
